### ISSUE TITLE
build crashes our installing postfix

### ISSUE THREAD

**Issue by enarcee** [mcci-catena/docker-ttn-dashboard#13]
routine crashes out in building postfix

Step 13/17 : run postmap /etc/postfix/generic
 ---> Running in 677f4c63c3f8
postmap: fatal: bad string length 0 < 1: mydomain =
ERROR: Service 'postfix' failed to build: The command '/bin/sh -c postmap /etc/postfix/generic' returned a non-zero code: 1

Any assistance appreciated. Thank you.

**Comment by enarcee** [comment]
there are some tricks to get postfix to build - otherwise it crashes out
add to postfix/Dockerfile
run postconf -e myhostname=myhost.mydomain.com   (replace $host_name variable)
run postconf -e mydomaine=mydomain.com

**Comment by oliv3** [comment]
Had exactly the same issue, @enarcee's fix works. Can this be integrated somehow ? Thanks !

**Comment by terrillmoore** [comment]
Sorry, missed this until now. (Pull requests always welcome..) Will look at this directly.

**Comment by terrillmoore** [comment]
Looks like it works. Thanks for the contribution!
