### ISSUE TITLE
Allow user to install extra nodes without editing Dockerfiles.

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/docker-ttn-dashboard#20]
See #17.

It would be nice to be able to push extra nodes through an environment variable -- something that iterates using bash, something like this:

```shell
RUN /bin/bash -c 'for iPkg in "$@" ; do npm install "$iPkg" || { echo "couldn't install: $iPkg" ; exit 1 ; } ; done' -- ${TTN_NODERED_PKGLIST}
```

Of course, I'd have to look up the other env var names and get the style right. And we'd need a test case.

**Comment by oliv3** [comment]
I came across https://github.com/mlopezr/node-red-docker
It's basically about adding nodes to the package.json file, if I get it correctly ?
cf https://github.com/node-red/node-red-docker/compare/master...mlopezr:master
