### ISSUE TITLE
Action required: Let's Encrypt certificate renewals

### ISSUE THREAD

**Issue by oliv3** [mcci-catena/docker-ttn-dashboard#22]
Hi,

Just received this email from letsencrypt.org:

>  Hello,
> 
> **Action is required to prevent your Let's Encrypt certificate renewals from breaking.**
> 
> Your Let’s Encrypt client used ACME TLS-SNI-01 domain validation to issue a certificate in the past 60 days.
> 
> TLS-SNI-01 validation is reaching end-of-life and will stop working on **February 13th, 2019.**
> 
> You need to update your ACME client to use an alternative validation method (HTTP-01, DNS-01 or TLS-ALPN-01) before this date or your certificate renewals will break and existing certificates will start to expire.
> 
> If you need help updating your ACME client, please open a new topic in the Help category of the Let's Encrypt community forum:
> 
>   https://community.letsencrypt.org/c/help
> 
> Please answer all of the questions in the topic template so we can help you.
> 
> For more information about the TLS-SNI-01 end-of-life please see our API announcement:
> 
> https://community.letsencrypt.org/t/february-13-2019-end-of-life-for-all-tls-sni-01-validation-support/74209
> 
> Thank you,
>   Let's Encrypt Staff
> 

My site has a cron job to renew, which pretty much looks like this one:

https://github.com/mcci-catena/docker-ttn-dashboard/blob/d667fe127ac9bde18c47aea5751178e3e0a216bb/apache/certbot_cron.sh#L8

From what I read on their forum, using `certbot renew --preferred-challenges http` would solve this issue.

What do you think ? Can send a PR if this looks ok to you.

Thanks,

**Comment by terrillmoore** [comment]
You beat me to it. I wasn't sure which of our sites had the problem because the email is uninformative. Thank you for finding this. 

Yes, please, send a PR and I'll merge.
