### ISSUE TITLE
At least one variable is not documented

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/docker-ttn-dashboard#33]
https://github.com/mcci-catena/docker-ttn-dashboard/blob/1614621265b7a051a70a1e966ebdf1a049808c18/docker-compose.yml#L167

`TTN_DASHBOARD_MAIL_HOST_NAME` is not documented in the commentary, and it's not clear what value should be provided here. (I think it's likely the dns name of the outer box, but.. it's not clear.  Convention is to document all variables, and to use the sed macro fixed in #28 to get the list for review.

**Comment by terrillmoore** [comment]
Yeah, i used git annotate. just figured I'd document the issue. I might as will build another script to check this. Maybe this can be a travis thing.

**Comment by oliv3** [comment]
I meant @MuruganChandrasekar introduced this variable in 6139aab

**Comment by terrillmoore** [comment]
Oh well, human error. If I had been serious, I would have doucmented the following command to get the list of undocumented, and unused, variables:

```shell
comm <(sed -n -e 's/#.*$//'  -e 's/[^$]*${\([^-:}]*\)[-:}][^$]*/\1/p' docker-compose.yml | LC_ALL=C sort -u)  <(sed -n -e '/^# TTN_[A-Z_0-9]*$/s/^# //p' docker-compose.yml | LC_ALL=C sort -u )
```

This (ugly) command uses [process substitution]() to produce two columns, one of undocumented names, another of documented-but-unused names:

```console
$ comm -3 <(sed -n -e 's/#.*$//'  -e 's/[^$]*${\([^-:}]*\)[-:}][^$]*/\1/p' docker-compose.yml | LC_ALL=C sort -u) <(sed -n -e '/^# TTN_[A-Z_0-9]*$/s/^# //p' docker-compose.yml | LC_ALL=C sort -u )
TTN_DASHBOARD_AWS_ACCESS_KEY_ID
TTN_DASHBOARD_AWS_DEFAULT_REGION
TTN_DASHBOARD_AWS_S3_BUCKET_INFLUXDB
TTN_DASHBOARD_AWS_SECRET_ACCESS_KEY
TTN_DASHBOARD_GRAFANA_SMTP_FROM_ADDRESS
	TTN_DASHBOARD_GRAFANA_SMTP_HOST_FQDN
TTN_DASHBOARD_MAIL_DOMAIN
TTN_DASHBOARD_MAIL_HOST_NAME
TTN_DASHBOARD_MAIL_RELAY_IP
```

So it seems there's some cleanup to be done. I'll document the command, and I'll at least document the variables minimally.

**Comment by oliv3** [comment]
I sure don't have your sed skills :)
I had an idea, which was to generate some .md from this file, so that one would not have to maintain the README at the same time.

**Comment by oliv3** [comment]
In fact, I was waiting for the sed magic to be OK before working on this idea, maybe this would need some additional markup in the comments, I don't know yet.
Also, the script/whatever could produce an example `.env` file with some example.com settings.
Finally, mentioning `docker-compose config` for checking things.
